### PR TITLE
Add request if needed

### PR DESCRIPTION
**Pull request by cozzin**
I want to show alert only when need to get permission, so I add `requestIfNeeded `.

### CODE REVIEW

**Comment by ivanvorobei** [comment]
Good idea.
Maybe add it func to readme?

**Comment by cozzin** [comment]
Ok, I will add func to readme.

**Comment by ivanvorobei** [comment]
@cozzin I found some trouble. You add changes in example project. Add it to `Source`, it available via cocoapods

**Comment by cozzin** [comment]
Thank you, I thought it is linked to original source. I will fix.

**Pull request merged**
